name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  push:
    branches:
      - main
  #schedule:
    # * is a special character in YAML so you have to quote this string
  #  - cron:  '* 15 * * *'
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt-get install -y xvfb ffmpeg
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: mkdir temp_file
      - run: npm install
      - run: sudo xvfb-run --auto-servernum npm run start