name: create-daily-track-video
run-name: creation of daily track video
on: workflow_dispatch
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - run: sudo ln -sf /usr/share/zoneinfo/Europe/Rome /etc/localtime
      - uses: actions/checkout@v3
      - run: sudo apt-get update
      - run: sudo apt-get install -y xvfb ffmpeg
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: mkdir -p temp_file
      - run: npm install
      - run: sudo xvfb-run --auto-servernum npm run start
